# 1) Write a python program to display all the header tags from wikipedia.org.

In [1]:
#Solution

import requests
from bs4 import BeautifulSoup

page1=requests.get('https://www.wikipedia.org/')
#page1
soup = BeautifulSoup(page1.content)

header_tags = soup.find_all(['h1', 'h2','h3','h4','h5','h6'])
print('List all the header tags :', *header_tags, sep='\n\n')

List all the header tags :

<h1 class="central-textlogo-wrapper">
<span class="central-textlogo__image sprite svg-Wikipedia_wordmark">
Wikipedia
</span>
<strong class="jsl10n localized-slogan" data-jsl10n="portal.slogan">The Free Encyclopedia</strong>
</h1>

<h2 class="bookshelf-container">
<span class="bookshelf">
<span class="text">
<bdi dir="ltr">
1 000 000+
</bdi>
<span class="jsl10n" data-jsl10n="entries">
articles
</span>
</span>
</span>
</h2>

<h2 class="bookshelf-container">
<span class="bookshelf">
<span class="text">
<bdi dir="ltr">
100 000+
</bdi>
<span class="jsl10n" data-jsl10n="portal.entries">
articles
</span>
</span>
</span>
</h2>

<h2 class="bookshelf-container">
<span class="bookshelf">
<span class="text">
<bdi dir="ltr">
10 000+
</bdi>
<span class="jsl10n" data-jsl10n="portal.entries">
articles
</span>
</span>
</span>
</h2>

<h2 class="bookshelf-container">
<span class="bookshelf">
<span class="text">
<bdi dir="ltr">
1 000+
</bdi>
<span class="jsl10n" data-jsl10n="portal.entries">
articles
</span>
</span>
</span>
</h2>

<h2 class="bookshelf-container">
<span class="bookshelf">
<span class="text">
<bdi dir="ltr">
100+
</bdi>
<span class="jsl10n" data-jsl10n="portal.entries">
articles
</span>
</span>
</span>
</h2>

# 2) Write a python program to display IMDB’s Top rated 100 movies’ data (i.e. name, rating, year of release) and make data frame.

In [2]:
#Solution

import pandas as pd
import requests
from bs4 import BeautifulSoup

page2=requests.get('https://www.imdb.com/search/title/?groups=top_100&sort=user_rating,desc&count=100')
#page2
soup2 = BeautifulSoup(page2.content, "html.parser")

Movie_name = []
Rating = []
Year_of_release = []

movie_data = soup2.findAll('div', attrs={'class':'lister-item mode-advanced'})

for i in movie_data:
    name = i.h3.a.text
    Movie_name.append(name)
    
    rate = i.find('div', class_= 'inline-block ratings-imdb-rating').text.replace('\n', '')
    Rating.append(rate)
    
    year = i.h3.find('span', class_= 'lister-item-year text-muted unbold').text.replace ('(','').replace(')','')
    Year_of_release.append(year)
    
       
df_movie=pd.DataFrame({'Movie name':Movie_name, 'Rating': Rating, 'Year of release':Year_of_release})
df_movie

                           Movie name Rating Year of release
0            The Shawshank Redemption    9.3            1994
1                       The Godfather    9.2            1972
2                     The Dark Knight    9.0            2008
3              The Godfather: Part II    9.0            1974
4                        12 Angry Men    9.0            1957
..                                ...    ...             ...
95                            Vertigo    8.3            1958
96                Singin' in the Rain    8.3            1952
97                Ladri di biciclette    8.3            1948
98                       Citizen Kane    8.3            1941
99  M - Eine Stadt sucht einen Mörder    8.3            1931

[100 rows x 3 columns]

# 3) Write a python program to display IMDB’s Top rated 100 Indian movies’ data (i.e. name, rating, year of release) and make data frame.

In [3]:
#Solution

import pandas as pd
import requests
from bs4 import BeautifulSoup

page3 = requests.get('https://www.imdb.com/list/ls009997493/')
#page3
soup3 = BeautifulSoup(page3.content, "html.parser")

Movie_name = []
Rating = []
Year_of_release = []

movie_data = soup3.findAll('div', attrs={'class':'lister-item-content'})

for store in movie_data:
    name = store.h3.a.text
    Movie_name.append(name)
    
    rate = store.find('div', class_= 'ipl-rating-star small').text.replace('\n', '')
    Rating.append(rate)
    
    year = store.h3.find('span', class_= 'lister-item-year text-muted unbold').text.replace ('(','').replace(')','')
    Year_of_release.append(year)
    
df_indian_movie=pd.DataFrame({'Movie name':Movie_name, 'Rating': Rating, 'Year of release':Year_of_release})
df_indian_movie

                Movie name Rating Year of release
0          Rang De Basanti    8.1            2006
1                 3 Idiots    8.4            2009
2         Taare Zameen Par    8.4            2007
3           Dil Chahta Hai    8.1            2001
4   Swades: We, the People    8.2            2004
..                     ...    ...             ...
95             Wake Up Sid    7.6            2009
96                Rangeela    7.5            1995
97     Shatranj Ke Khilari    7.7            1977
98      Pyaar Ka Punchnama    7.6            2011
99           Ek Hasina Thi    7.5            2004

[100 rows x 3 columns]

# 4) Write a python program to scrape cricket rankings from icc-cricket.com. You have to scrape:
a) Top 10 ODI teams in men’s cricket along with the records for matches, points and rating.
b) Top 10 ODI Batsmen in men along with the records of their team and rating.
c) Top 10 ODI bowlers along with the records of their team and rating.

In [6]:
#Solution

import requests
from bs4 import BeautifulSoup
 
print('---------------------------------------------------------------------------------')
print('(a)Top 10 ODI teams in men’s cricket along with the records for matches, points and rating.')
print('---------------------------------------------------------------------------------')
page4a=requests.get('https://www.icc-cricket.com/rankings/mens/team-rankings/odi')
#page4a
soup4a = BeautifulSoup(page4a.content, "html.parser")     
 
for tr in soup4a.find_all('tr'):
    tds = []
    for th in tr.find_all('th'):
        tds.append(th.text.replace('\n',' '))
        
    for td in tr.find_all('td'):
        tds.append(td.text.replace('\n',' ').strip())
        
    print(tds)
    

print('---------------------------------------------------------------------------------')
print('(b) Top 10 ODI Batsmen in men along with the records of their team and rating.')
print('---------------------------------------------------------------------------------')
page4b=requests.get('https://www.icc-cricket.com/rankings/mens/player-rankings/odi/batting')
#page4b
soup4b = BeautifulSoup(page4b.content, "html.parser") 
 
for tr in soup4b.find_all('tr'):
    mds = []
    for th in tr.find_all('th'):
        mds.append(th.text.replace('\n',' '))
        
    for td in tr.find_all('td'):
        mds.append(td.text.replace('(0)',' ').strip())
        
    print(mds)
    
       
print('---------------------------------------------------------------------------------')
print('(c) Top 10 ODI bowlers along with the records of their team and rating.')
print('---------------------------------------------------------------------------------')
page4c=requests.get('https://www.icc-cricket.com/rankings/mens/player-rankings/odi/bowling')
#page4c
soup4c = BeautifulSoup(page4c.content, "html.parser")  
 
for tr in soup4c.find_all('tr'):
    alls = []
    for th in tr.find_all('th'):
        alls.append(th.text.replace('\n',' '))
        
    for td in tr.find_all('td'):
        alls.append(td.text.replace('(0)',' ').strip())
        
    print(alls)

---------------------------------------------------------------------------------
(a)Top 10 ODI teams in men’s cricket along with the records for matches, points and rating.
---------------------------------------------------------------------------------
['Pos', ' Team T ', ' Matches M ', ' Points P ', ' Rating R ']
['1', 'New Zealand NZ', '17', '2,054', '121']
['2', 'England ENG', '32', '3,793', '119']
['3', 'Australia AUS', '28', '3,244', '116']
['4', 'India IND', '32', '3,624', '113']
['5', 'South Africa SA', '25', '2,459', '98']
['6', 'Pakistan PAK', '27', '2,524', '93']
['7', 'Bangladesh BAN', '30', '2,740', '91']
['8', 'West Indies WI', '30', '2,523', '84']
['9', 'Sri Lanka SL', '32', '2,657', '83']
['10', 'Afghanistan AFG', '17', '1,054', '62']
['11', 'Netherlands NED', '7', '336', '48']
['12', 'Ireland IRE', '25', '1,145', '46']
['13', 'Scotland SCO', '10', '452', '45']
['14', 'Zimbabwe ZIM', '20', '764', '38']
['15', 'Oman OMA', '14', '524', '37']
['16', 'Nepal NEP', '11', '330', '30']
['17', 'UAE UAE', '9', '190', '21']
['18', 'United States USA', '14', '232', '17']
['19', 'Namibia NAM', '6', '97', '16']
['20', 'Papua New Guinea PNG', '13', '0', '0']
---------------------------------------------------------------------------------
(b) Top 10 ODI Batsmen in men along with the records of their team and rating.
---------------------------------------------------------------------------------
['Pos', 'Player', 'Team', 'Rating', 'Career Best Rating']
['1', 'Babar Azam', 'PAK']
['2', 'Virat Kohli', 'IND', '844', '911 v England, 12/07/2018']
['3', 'Rohit Sharma', 'IND', '813', '885 v Sri Lanka, 06/07/2019']
['4', 'Ross Taylor', 'NZ', '801', '841 v Bangladesh, 05/06/2019']
['5', 'Aaron Finch', 'AUS', '779', '798 v England, 25/06/2019']
['6', 'Jonny Bairstow', 'ENG', '775', '796 v India, 26/03/2021']
['7', 'David Warner', 'AUS', '762', '880 v Pakistan, 26/01/2017']
['8', 'Shai Hope', 'WI', '758', '808 v Bangladesh, 17/05/2019']
['9', 'Kane Williamson', 'NZ', '754', '799 v India, 09/07/2019']
['10', 'Quinton de Kock', 'SA', '743', '813 v Sri Lanka, 10/03/2019']
['11', 'Fakhar Zaman', 'PAK', '741', '779 v England, 08/07/2021']
['12', 'Joe Root', 'ENG', '740', '824 v Sri Lanka, 13/10/2018']
['13', 'Mushfiqur Rahim', 'BAN', '723', '739 v Sri Lanka, 25/05/2021']
['14', 'Imam-ul-Haq', 'PAK', '717', '768 v South Africa, 02/04/2021']
['15', 'Martin Guptill', 'NZ', '707', '789 v South Africa, 01/03/2017']
['16', 'Shikhar Dhawan', 'IND', '704', '813 v Pakistan, 23/09/2018']
['17', 'Steve Smith', 'AUS', '696', '752 v Pakistan, 22/01/2017']
['18', 'Jason Roy', 'ENG', '687', '782 v Australia, 11/07/2019']
['19', 'Glenn Maxwell', 'AUS', '674', '735 v India, 20/01/2016']
['20', 'Rassie van der Dussen', 'SA', '671', '689 v Sri Lanka, 02/09/2021']
['21', 'Tamim Iqbal', 'BAN', '670', '737 v West Indies, 28/07/2018']
['22', 'Alex Carey', 'AUS', '669', '669 v West Indies, 26/07/2021']
['23', 'Paul Stirling', 'IRE', '658', '697 v Netherlands, 04/06/2021']
['24', 'Ben Stokes', 'ENG', '651', '694 v New Zealand, 14/07/2019']
['25', 'Eoin Morgan', 'ENG', '650', '720 v Afghanistan, 18/06/2019']
['26', 'Shakib Al Hasan', 'BAN', '641', '692 v Pakistan, 05/07/2019']
['27', 'Lokesh Rahul', 'IND', '636', '657 v England, 26/03/2021']
['28', 'Tom Latham', 'NZ', '624', '631 v Bangladesh, 23/03/2021']
['29', 'Nicholas Pooran', 'WI', '615', '634 v Ireland, 12/01/2020']
['30', 'David Miller', 'SA', '615', '643 v Pakistan, 04/04/2021']
['31', 'Jos Buttler', 'ENG', '608', '741 v Bangladesh, 08/06/2019']
['32', 'Shimron Hetmyer', 'WI', '607', '709 v India, 15/12/2019']
['33', 'Janneman Malan', 'SA', '605', '605 v Netherlands, 26/11/2021']
['34', 'Haris Sohail', 'PAK', '594', '618 v Zimbabwe, 30/10/2020']
['35', 'Henry Nicholls', 'NZ', '581', '596 v Bangladesh, 20/03/2021']
['36', 'Kyle Coetzer', 'SCO', '575', '647 v Ireland, 18/03/2018']
['37\n                                \n\n\n\n\n(4)\nThis player has moved up in the rankings since the previous rankings update', 'Aqib Ilyas', 'OMA', '574', '578 v United States, 11/02/2020']
['38\n                                \n\n\n\n\n(1)\nThis player has moved down in the rankings since the previous rankings update', 'Mahmudullah', 'BAN', '571', '582 v Sri Lanka, 28/05/2021']
['39\n                                \n\n\n\n\n(1)\nThis player has moved down in the rankings since the previous rankings update', 'Brendan Taylor', 'ZIM', '569', '667 v New Zealand, 09/02/2012']
['40\n                                \n\n\n\n\n(1)\nThis player has moved down in the rankings since the previous rankings update', 'Avishka Fernando', 'SL', '568', '591 v South Africa, 02/09/2021']
['41\n                                \n\n\n\n\n(1)\nThis player has moved down in the rankings since the previous rankings update', 'Andrew Balbirnie', 'IRE', '568', '584 v South Africa, 13/07/2021']
['42', 'Rahmat Shah', 'AFG', '559', '625 v Sri Lanka, 17/09/2018']
['43', 'Evin Lewis', 'WI', '558', '567 v Sri Lanka, 12/03/2021']
['44', 'Litton Das', 'BAN', '558', '573 v Zimbabwe, 06/03/2020']
['45', 'Kedar Jadhav', 'IND', '552', '629 v Afghanistan, 22/06/2019']
['46', 'Kusal Perera', 'SL', '551', '582 v England, 29/06/2021']
['47', 'Hardik Pandya', 'IND', '548', '561 v England, 28/03/2021']
['48', 'Sean Williams', 'ZIM', '545', '561 v Pakistan, 03/11/2020']
['49', 'Sikandar Raza', 'ZIM', '542', '576 v Afghanistan, 22/10/2015']
['50', 'Angelo Mathews', 'SL', '542', '707 v England, 07/12/2014']
['51', 'Danushka Gunathilaka', 'SL', '530', '554 v Bangladesh, 28/05/2021']
['52', 'Imad Wasim', 'PAK', '525', '556 v Bangladesh, 05/07/2019']
['53', 'Soumya Sarkar', 'BAN', '521', '671 v South Africa, 15/07/2015']
['54', 'Kusal Mendis', 'SL', '518', '631 v Zimbabwe, 30/06/2017']
['55', 'Marcus Stoinis', 'AUS', '517', '616 v India, 08/03/2019']
['56', 'Colin de Grandhomme', 'NZ', '507', '520 v Pakistan, 19/01/2018']
['57', 'Najibullah Zadran', 'AFG', '506', '518 v West Indies, 09/11/2019']
['58', 'Sarfaraz Ahmed', 'PAK', '504', '581 v West Indies, 05/10/2016']
['59', 'Calum MacLeod', 'SCO', '500', '585 v England, 10/06/2018']
['60', 'Hashmatullah Shaidi', 'AFG', '498', '519 v India, 22/06/2019']
['61', 'Marnus Labuschagne', 'AUS', '498', '532 v India, 29/11/2020']
['62', 'Jimmy Neesham', 'NZ', '495', '549 v Pakistan, 26/06/2019']
['63', 'Niroshan Dickwella', 'SL', '495', '518 v Bangladesh, 28/05/2021']
['64', 'Mohammad Nabi', 'AFG', '494', '545 v Bangladesh, 28/09/2016']
['65', 'Mitchell Marsh', 'AUS', '489', '641 v New Zealand, 06/12/2016']
['66', 'Richard Berrington', 'SCO', '487', '491 v Oman, 28/09/2021']
['67', 'Kariyawasa Asalanka', 'SL', '484', '484 v South Africa, 07/09/2021']
['68', 'William Porterfield', 'IRE', '484', '539 v UAE, 12/03/2018']
['69', 'Asghar Afghan', 'AFG', '479', '483 v West Indies, 11/11/2019']
['70', 'Harry Tector', 'IRE', '477', '477 v Zimbabwe, 13/09/2021']
['71', 'Assad Vala', 'PNG', '476', '476 v Oman, 01/10/2021']
['72', 'Craig Ervine', 'ZIM', '476', '524 v Afghanistan, 18/10/2015']
['73', 'Aiden Markram', 'SA', '476', '485 v Sri Lanka, 04/09/2021']
['74', 'Heinrich Klaasen', 'SA', '474', '499 v Australia, 07/03/2020']
['75', 'Dhananjaya de Silva', 'SL', '473', '482 v England, 01/07/2021']
['76', 'Shreyas Iyer', 'IND', '472', '513 v New Zealand, 11/02/2020']
['77', 'Muhammad Usman', 'UAE', '471', '478 v Ireland, 08/01/2021']
['78', 'George Munsey', 'SCO', '464', '464 v Oman, 02/10/2021']
['79', 'Mitchell Santner', 'NZ', '460', '502 v England, 10/03/2018']
['80', 'Temba Bavuma', 'SA', '460', '467 v Sri Lanka, 02/09/2021']
['81', 'Jason Holder', 'WI', '446', '455 v Australia, 22/07/2021']
['82', 'Andile Phehlukwayo', 'SA', '440', '450 v Pakistan, 07/04/2021']
['83', 'Ravindra Jadeja', 'IND', '434', '552 v West Indies, 08/10/2014']
['84', 'Mithun Ali', 'BAN', '433', '452 v New Zealand, 23/03/2021']
['85', 'Rashid Khan', 'AFG', '432', '477 v Ireland, 10/03/2019']
['86', 'Lahiru Thirimanne', 'SL', '429', '599 v West Indies, 04/11/2015']
['87', 'Rishabh Pant', 'IND', '426', '432 v England, 28/03/2021']
['88', 'Dasun Shanaka', 'SL', '424', '424 v South Africa, 07/09/2021']
['89', 'Matthew Wade', 'AUS', '424', '553 v Pakistan, 15/01/2017']
['90', 'Rovman Powell', 'WI', '419', '456 v India, 24/10/2018']
['91', 'Kieron Pollard', 'WI', '416', '602 v Zimbabwe, 24/02/2013']
['92', 'Gulbadin Naib', 'AFG', '415', '440 v Ireland, 28/02/2018']
['93', 'Mohammad Rizwan', 'PAK', '414', '426 v Australia, 29/03/2019']
['94', 'Curtis Campher', 'IRE', '412', '418 v South Africa, 16/07/2021']
['95', 'Dinesh Chandimal', 'SL', '409', '667 v Australia, 02/03/2012']
['96\n                                \n\n\n\n\n(2)\nThis player has moved up in the rankings since the previous rankings update', 'Zeeshan Maqsood', 'OMA', '407', '407 v Namibia, 27/11/2021']
['97\n                                \n\n\n\n\n(1)\nThis player has moved down in the rankings since the previous rankings update', "Max O'Dowd", 'NED', '406', '406 v South Africa, 26/11/2021']
['98\n                                \n\n\n\n\n(1)\nThis player has moved down in the rankings since the previous rankings update', 'Matthew Cross', 'SCO', '405', '427 v Oman, 18/08/2019']
['99', 'Moeen Ali', 'ENG', '404', '522 v West Indies, 27/09/2017']
['100', 'Chris Woakes', 'ENG', '403', '481 v Australia, 26/01/2018']
---------------------------------------------------------------------------------
(c) Top 10 ODI bowlers along with the records of their team and rating.
---------------------------------------------------------------------------------
['Pos', 'Player', 'Team', 'Rating', 'Career Best Rating']
['1', 'Trent Boult', 'NZ']
['2', 'Josh Hazlewood', 'AUS', '709', '733 v England, 26/01/2018']
['3', 'Mujeeb Ur Rahman', 'AFG', '708', '712 v Ireland, 24/01/2021']
['4', 'Chris Woakes', 'ENG', '700', '711 v Sri Lanka, 04/07/2021']
['5', 'Mehedi Hasan', 'BAN', '692', '725 v Sri Lanka, 25/05/2021']
['6', 'Matt Henry', 'NZ', '691', '691 v Bangladesh, 26/03/2021']
['7', 'Jasprit Bumrah', 'IND', '679', '841 v West Indies, 01/11/2018']
['8', 'Mitchell Starc', 'AUS', '652', '783 v New Zealand, 29/03/2015']
['9', 'Shakib Al Hasan', 'BAN', '650', '717 v Zimbabwe, 05/11/2009']
['10', 'Kagiso Rabada', 'SA', '643', '724 v England, 29/05/2017']
['11', 'Mustafizur Rahman', 'BAN', '640', '695 v West Indies, 14/12/2018']
['12', 'Pat Cummins', 'AUS', '636', '729 v Pakistan, 12/06/2019']
['13', 'Shaheen Afridi', 'PAK', '630', '637 v England, 10/07/2021']
['14', 'Mohammad Amir', 'PAK', '628', '663 v Sri Lanka, 02/10/2019']
['15', 'Rashid Khan', 'AFG', '626', '806 v Pakistan, 21/09/2018']
['16', 'Adam Zampa', 'AUS', '625', '625 v West Indies, 26/07/2021']
['17', 'Bhuvneshwar Kumar', 'IND', '621', '657 v West Indies, 17/10/2014']
['18', 'Lachlan Ferguson', 'NZ', '619', '668 v West Indies, 22/06/2019']
['19', 'Jofra Archer', 'ENG', '609', '642 v Australia, 13/09/2020']
['20', 'Yuzvendra Chahal', 'IND', '603', '730 v New Zealand, 23/01/2019']
['21', 'Mohammad Nabi', 'AFG', '596', '653 v Zimbabwe, 26/02/2017']
['22', 'Mark Wood', 'ENG', '594', '615 v Afghanistan, 18/06/2019']
['23', 'Alzarri Joseph', 'WI', '592', '594 v Australia, 22/07/2021']
['24', 'Lungi Ngidi', 'SA', '587', '621 v Australia, 04/03/2020']
['25', 'Mitchell Santner', 'NZ', '583', '663 v England, 25/02/2018']
['26', 'Akila Dananjaya', 'SL', '583', '651 v England, 23/10/2018']
['27', 'Andy McBrine', 'IRE', '579', '579 v Zimbabwe, 13/09/2021']
['28', 'Mohammad Shami', 'IND', '566', '654 v Bangladesh, 19/03/2015']
['29', 'Kuldeep Yadav', 'IND', '562', '765 v New Zealand, 26/01/2019']
['30', 'Ravindra Jadeja', 'IND', '550', '738 v Zimbabwe, 01/08/2013']
['31', 'Tabraiz Shamsi', 'SA', '546', '562 v Sri Lanka, 07/09/2021']
['32', 'Sheldon Cottrell', 'WI', '541', '581 v Sri Lanka, 26/02/2020']
['33', 'Wanindu Hasaranga', 'SL', '531', '531 v South Africa, 07/09/2021']
['34', 'Ahmed Raza', 'UAE', '531', '531 v Ireland, 18/01/2021']
['35', 'Dushmantha Chameera', 'SL', '525', '538 v England, 29/06/2021']
['36', 'Mark Watt', 'SCO', '519', '529 v Papua New Guinea, 29/09/2021']
['37', 'Shadab Khan', 'PAK', '517', '607 v South Africa, 22/01/2019']
['38', 'Colin de Grandhomme', 'NZ', '508', '522 v India, 11/02/2020']
['39', 'Simi Singh', 'IRE', '507', '507 v Zimbabwe, 13/09/2021']
['40', 'David Willey', 'ENG', '501', '551 v Sri Lanka, 02/07/2016']
['41', 'Tim Southee', 'NZ', '500', '638 v England, 20/02/2015']
['42', 'Adil Rashid', 'ENG', '497', '687 v Sri Lanka, 20/10/2018']
['43', 'Ish Sodhi', '', '496', '']
['44', 'Imad Wasim', 'PAK', '488', '570 v England, 19/05/2019']
['45', 'Hasan Ali', 'PAK', '483', '766 v New Zealand, 06/01/2018']
['46', 'Usman Khan', 'PAK', '482', '504 v Sri Lanka, 02/10/2019']
['47', 'Jhye Richardson', 'AUS', '480', '548 v Pakistan, 24/03/2019']
['48', 'Rohan Mustafa', 'UAE', '477', '477 v Ireland, 18/01/2021']
['49', 'Keshav Maharaj', 'SA', '476', '494 v Sri Lanka, 07/09/2021']
['50', 'Blessing Muzarabani', 'ZIM', '470', '470 v Ireland, 13/09/2021']
['51', 'Mashrafe Mortaza', 'BAN', '469', '653 v Zimbabwe, 23/01/2009']
['52', 'Mohammad Mohammad Saifuddin', 'BAN', '468', '496 v West Indies, 25/01/2021']
['53\n                                \n\n\n\n\n(9)\nThis player has moved up in the rankings since the previous rankings update', 'Zeeshan Maqsood', 'OMA', '465', '465 v Namibia, 27/11/2021']
['54\n                                \n\n\n\n\n(1)\nThis player has moved down in the rankings since the previous rankings update', 'Joshua Little', 'IRE', '463', '463 v Zimbabwe, 13/09/2021']
['55\n                                \n\n\n\n\n(1)\nThis player has moved down in the rankings since the previous rankings update', 'Jimmy Neesham', 'NZ', '458', '458 v Bangladesh, 26/03/2021']
['56\n                                \n\n\n\n\n(1)\nThis player has moved down in the rankings since the previous rankings update', 'Tendai Chatara', 'ZIM', '458', '562 v Ireland, 07/03/2015']
['57\n                                \n\n\n\n\n(1)\nThis player has moved down in the rankings since the previous rankings update', 'Andile Phehlukwayo', 'SA', '456', '613 v Pakistan, 30/01/2019']
['58\n                                \n\n\n\n\n(1)\nThis player has moved down in the rankings since the previous rankings update', 'Saqib Mahmood', 'ENG', '454', '454 v Pakistan, 13/07/2021']
['59\n                                \n\n\n\n\n(1)\nThis player has moved down in the rankings since the previous rankings update', 'Nuwan Pradeep', 'SL', '453', '506 v England, 13/10/2018']
['60\n                                \n\n\n\n\n(1)\nThis player has moved down in the rankings since the previous rankings update', 'Jason Holder', 'WI', '451', '486 v Sri Lanka, 10/03/2021']
['61\n                                \n\n\n\n\n(1)\nThis player has moved down in the rankings since the previous rankings update', 'Moeen Ali', 'ENG', '449', '629 v Australia, 24/06/2018']
['62\n                                \n\n\n\n\n(1)\nThis player has moved down in the rankings since the previous rankings update', 'Wahab Riaz', 'PAK', '447', '522 v England, 13/11/2015']
['63', 'Faheem Ashraf', 'PAK', '445', '477 v South Africa, 02/04/2021']
['64', 'Akeal Hosein', 'WI', '443', '443 v Australia, 26/07/2021']
['65', 'Tom Curran', 'ENG', '436', '443 v Sri Lanka, 04/07/2021']
['66', 'Safyaan Sharif', 'SCO', '436', '542 v England, 10/06/2018']
['67', 'Suranga Lakmal', 'SL', '436', '594 v Bangladesh, 25/01/2018']
['68', 'Ashton Agar', 'AUS', '436', '436 v West Indies, 26/07/2021']
['69', 'Taskin Ahmed', 'BAN', '434', '456 v Sri Lanka, 28/03/2017']
['70', 'Anrich Nortje', 'SA', '429', '436 v Sri Lanka, 02/09/2021']
['71', 'Sikandar Raza', 'ZIM', '424', '494 v UAE, 16/04/2019']
['72\n                                \n\n\n\n\n(2)\nThis player has moved up in the rankings since the previous rankings update', 'Bilal Khan', 'OMA', '422', '422 v Namibia, 27/11/2021']
['73\n                                \n\n\n\n\n(1)\nThis player has moved down in the rankings since the previous rankings update', 'Saurabh Netravalkar', 'USA', '419', '419 v Oman, 20/09/2021']
['74\n                                \n\n\n\n\n(1)\nThis player has moved down in the rankings since the previous rankings update', 'Josh Davey', 'SCO', '418', '436 v UAE, 15/12/2019']
['75', 'Kane Richardson', 'AUS', '416', '448 v India, 17/01/2020']
['76', 'Sean Williams', 'ZIM', '413', '474 v Sri Lanka, 30/06/2017']
['77', 'Ben Stokes', 'ENG', '410', '474 v New Zealand, 03/07/2019']
['78', 'Alasdair Evans', 'SCO', '408', '421 v England, 10/06/2018']
['79', 'Shardul Thakur', 'IND', '405', '411 v England, 28/03/2021']
['80', 'Craig Young', 'IRE', '405', '421 v South Africa, 16/07/2021']
['81', 'Dhananjaya de Silva', 'SL', '401', '412 v Bangladesh, 23/05/2021']
['82', 'Sandeep Lamichhane', 'NEP', '400', '400 v Oman, 19/09/2021']
['83', 'Rubel Hossain', 'BAN', '400', '514 v Pakistan, 01/12/2011']
['84', 'Gulbadin Naib', 'AFG', '399', '472 v Ireland, 21/05/2019']
['85', 'Chad Soper', 'PNG', '397', '399 v Oman, 26/09/2021']
['86', 'Hardik Pandya', 'IND', '394', '552 v South Africa, 16/02/2018']
['87', 'Mitchell Marsh', 'AUS', '390', '511 v New Zealand, 04/12/2016']
['88', 'Wayne Parnell', 'SA', '387', '550 v West Indies, 28/01/2015']
['89', 'Barry McCarthy', 'IRE', '385', '448 v West Indies, 09/01/2020']
['90', 'Fred Klaassen', 'NED', '383', '383 v South Africa, 26/11/2021']
['91', 'Nosaina Pokana', 'PNG', '380', '384 v Oman, 26/09/2021']
['92', 'Marcus Stoinis', 'AUS', '377', '426 v England, 25/06/2019']
['93', 'Michael Leask', 'SCO', '374', '382 v Papua New Guinea, 29/09/2021']
['94', 'Taijul Islam', 'BAN', '374', '397 v Zimbabwe, 06/03/2020']
['95', 'Mohammad Nawaz', 'PAK', '370', '376 v South Africa, 07/04/2021']
['96', 'Assad Vala', 'PNG', '370', '370 v Oman, 01/10/2021']
['97', 'Lakshan Sandakan', 'SL', '370', '383 v Bangladesh, 25/05/2021']
['98', 'Donald Tiripano', 'ZIM', '362', '373 v Pakistan, 03/11/2020']
['99', 'Oshane Thomas', 'WI', '355', '419 v Australia, 06/06/2019']
['100', 'Kyle Jamieson', 'NZ', '352', '352 v Bangladesh, 26/03/2021']

# 5) Write a python program to scrape cricket rankings from icc-cricket.com. You have to scrape:
a) Top 10 ODI teams in women’s cricket along with the records for matches, points and rating.
b) Top 10 women’s ODI players along with the records of their team and rating.
c) Top 10 women’s ODI all-rounder along with the records of their team and rating.

In [7]:
#Solution

import requests
from bs4 import BeautifulSoup
 
print('---------------------------------------------------------------------------------')
print('(a)Top 10 ODI teams in women’s cricket along with the records for matches, points and rating.')
print('---------------------------------------------------------------------------------')
page5a=requests.get('https://www.icc-cricket.com/rankings/womens/team-rankings/odi')
#page5a
soup5a = BeautifulSoup(page5a.content, "html.parser")     
 
for tr in soup5a.find_all('tr'):
    tds = []
    for th in tr.find_all('th'):
        tds.append(th.text.replace('\n',' '))
        
    for td in tr.find_all('td'):
        tds.append(td.text.replace('\n',' ').strip())
        
    print(tds)
    

print('---------------------------------------------------------------------------------')
print('(b) Top 10 women’s ODI players along with the records of their team and rating.')
print('---------------------------------------------------------------------------------')
page5b=requests.get('https://www.icc-cricket.com/rankings/womens/player-rankings/odi/batting')
#page5b
soup5b = BeautifulSoup(page5b.content, "html.parser") 
 
for tr in soup5b.find_all('tr'):
    mds = []
    for th in tr.find_all('th'):
        mds.append(th.text.replace('\n',' '))
        
    for td in tr.find_all('td'):
        mds.append(td.text.replace('(0)',' ').strip())
        
    print(mds)
    
       
print('---------------------------------------------------------------------------------')
print('(C) Top 10 women’s ODI all-rounder along with the records of their team and rating.')
print('---------------------------------------------------------------------------------')
page5c=requests.get('https://www.icc-cricket.com/rankings/womens/player-rankings/odi/all-rounder')
#page5c
soup5c = BeautifulSoup(page5c.content, "html.parser")  
 
for tr in soup5c.find_all('tr'):
    alls = []
    for th in tr.find_all('th'):
        alls.append(th.text.replace('\n',' '))
        
    for td in tr.find_all('td'):
        alls.append(td.text.replace('(0)',' ').strip())
        
    print(alls)

---------------------------------------------------------------------------------
(a)Top 10 ODI teams in women’s cricket along with the records for matches, points and rating.
---------------------------------------------------------------------------------
['Pos', ' Team T ', ' Matches M ', ' Points P ', ' Rating R ']
['1', 'Australia AUS', '17', '2,746', '162']
['2', 'South Africa SA', '19', '2,307', '121']
['3', 'England ENG', '18', '2,148', '119']
['4', 'India IND', '17', '1,899', '112']
['5', 'Bangladesh BAN', '5', '475', '95']
['6', 'New Zealand NZ', '19', '1,668', '88']
['7', 'West Indies WI', '19', '1,658', '87']
['8', 'Pakistan PAK', '18', '1,226', '68']
['9', 'Ireland IRE', '5', '240', '48']
['10', 'Sri Lanka SL', '5', '233', '47']
['11', 'Zimbabwe ZIM', '7', '0', '0']
---------------------------------------------------------------------------------
(b) Top 10 women’s ODI players along with the records of their team and rating.
---------------------------------------------------------------------------------
['Pos', 'Player', 'Team', 'Rating', 'Career Best Rating']
['1', 'Lizelle Lee', 'SA']
['2', 'Alyssa Healy', 'AUS', '750', '776 v India, 21/09/2021']
['3', 'Mithali Raj', 'IND', '738', '839 v Australia, 24/12/2004']
['4', 'Tammy Beaumont', 'ENG', '728', '791 v India, 27/06/2021']
['5', 'Amy Satterthwaite', 'NZ', '717', '756 v Australia, 02/03/2017']
['6', 'Smriti Mandhana', 'IND', '710', '797 v England, 28/02/2019']
['7', 'Meg Lanning', 'AUS', '699', '834 v New Zealand, 24/02/2016']
['8', 'Beth Mooney', 'AUS', '690', '690 v India, 26/09/2021']
['9', 'Stafanie Taylor', 'WI', '676', '766 v Pakistan, 07/07/2021']
['10', 'Heather Knight', 'ENG', '674', '693 v West Indies, 06/06/2019']
['11', 'Laura Wolvaardt', 'SA', '672', '725 v India, 07/03/2021']
['12', 'Rachael Haynes', 'AUS', '668', '699 v India, 21/09/2021']
['13', 'Ellyse Perry', 'AUS', '649', '766 v West Indies, 11/09/2019']
['14', 'Mignon du Preez', 'SA', '648', '648 v West Indies, 19/09/2021']
['15', 'Natalie Sciver', 'ENG', '642', '712 v India, 25/02/2019']
['16', 'Deandra Dottin', 'WI', '578', '650 v New Zealand, 06/10/2013']
['17', 'Sophie Devine', 'NZ', '563', '678 v Australia, 03/03/2019']
['18', 'Harmanpreet Kaur', 'IND', '559', '679 v South Africa, 28/11/2014']
['19', 'Chamari Athapaththu', 'SL', '552', '691 v South Africa, 14/02/2019']
['20', 'Deepti Sharma', 'IND', '543', '622 v South Africa, 09/10/2019']
['21', 'Marizanne Kapp', 'SA', '538', '569 v Pakistan, 23/01/2021']
['22', 'Amy Jones', 'ENG', '537', '564 v West Indies, 13/06/2019']
['23', 'Poonam Raut', 'IND', '537', '606 v South Africa, 14/03/2021']
['24', 'Suzie Bates', 'NZ', '530', '775 v Australia, 24/02/2016']
['25', 'Fargana Hoque', 'BAN', '512', '512 v Pakistan, 21/11/2021']
['26\n                                \n\n\n\n\n(6)\nThis player has moved up in the rankings since the previous rankings update', 'Aliya Riaz', 'PAK', '504', '504 v Zimbabwe, 27/11/2021']
['27\n                                \n\n\n\n\n(1)\nThis player has moved down in the rankings since the previous rankings update', 'Dane van Niekerk', 'SA', '489', '677 v Sri Lanka, 11/02/2019']
['28\n                                \n\n\n\n\n(1)\nThis player has moved down in the rankings since the previous rankings update', 'Ashleigh Gardner', 'AUS', '477', '477 v India, 26/09/2021']
['29\n                                \n\n\n\n\n(1)\nThis player has moved down in the rankings since the previous rankings update', 'Hayley Matthews', 'WI', '477', '535 v Pakistan, 12/07/2021']
['30\n                                \n\n\n\n\n(1)\nThis player has moved down in the rankings since the previous rankings update', 'Rumana Ahmed', 'BAN', '476', '476 v Pakistan, 21/11/2021']
['31', 'Danielle Wyatt', 'ENG', '466', '466 v New Zealand, 26/09/2021']
['32\n                                \n\n\n\n\n(2)\nThis player has moved down in the rankings since the previous rankings update', 'Nahida Khan', 'PAK', '458', '603 v England, 14/12/2019']
['33\n                                \n\n\n\n\n(3)\nThis player has moved up in the rankings since the previous rankings update', 'Javeria Khan', 'PAK', '457', '573 v South Africa, 15/03/2015']
['34\n                                \n\n\n\n\n(1)\nThis player has moved down in the rankings since the previous rankings update', 'Brooke Halliday', 'NZ', '449', '449 v England, 26/09/2021']
['35\n                                \n\n\n\n\n(1)\nThis player has moved down in the rankings since the previous rankings update', 'Gaby Lewis', 'IRE', '438', '438 v West Indies, 23/11/2021']
['36\n                                \n\n\n\n\n(1)\nThis player has moved up in the rankings since the previous rankings update', 'Nida Dar', 'PAK', '425', '425 v Bangladesh, 21/11/2021']
['37\n                                \n\n\n\n\n(2)\nThis player has moved down in the rankings since the previous rankings update', 'Bismah Maroof', 'PAK', '425', '570 v New Zealand, 13/11/2016']
['38', 'Maddie Green', 'NZ', '424', '437 v England, 21/09/2021']
['39', 'Katherine Brunt', 'ENG', '409', '426 v New Zealand, 21/09/2021']
['40', 'Lauren Winfield', 'ENG', '403', '403 v New Zealand, 26/09/2021']
['41', 'Laura Delany', 'IRE', '393', '408 v Zimbabwe, 11/10/2021']
['42', 'Chloe-Lesleigh Tryon', 'SA', '386', '548 v Pakistan, 12/05/2019']
['43\n                                \n\n\n\n\n(1)\nThis player has moved up in the rankings since the previous rankings update', 'Katey Martin', 'NZ', '377', '483 v Australia, 05/03/2017']
['44\n                                \n\n\n\n\n(1)\nThis player has moved up in the rankings since the previous rankings update', 'Katie Perkins', 'NZ', '373', '503 v South Africa, 25/01/2020']
['45\n                                \n\n\n\n\n(2)\nThis player has moved down in the rankings since the previous rankings update', 'Umaima Sohail', 'PAK', '369', '408 v West Indies, 14/11/2021']
['46', 'Amelia Kerr', 'NZ', '358', '409 v Australia, 07/04/2021']
['47', 'Jess Jonassen', 'AUS', '358', '410 v England, 07/07/2019']
['48', 'Sune Luus', 'SA', '350', '469 v England, 05/07/2017']
['49', 'Tahlia McGrath', 'AUS', '349', '349 v India, 26/09/2021']
['50', 'Jhulan Goswami', 'IND', '346', '430 v New Zealand, 28/06/2015']
['51', 'Trisha Chetty', 'SA', '345', '585 v Ireland, 09/08/2016']
['52', 'Harshitha Madavi', 'SL', '336', '356 v Australia, 09/10/2019']
['53', 'Shafali Verma', 'IND', '330', '330 v Australia, 26/09/2021']
['54\n                                \n\n\n\n\n(2)\nThis player has moved up in the rankings since the previous rankings update', 'Muneeba Ali', 'PAK', '320', '320 v Zimbabwe, 27/11/2021']
['55\n                                \n\n\n\n\n(1)\nThis player has moved down in the rankings since the previous rankings update', 'Leah Paul', 'IRE', '318', '318 v West Indies, 23/11/2021']
['56\n                                \n\n\n\n\n(1)\nThis player has moved down in the rankings since the previous rankings update', 'Nicola Carey', 'AUS', '317', '317 v India, 26/09/2021']
['57', 'Dilani Manodara', 'SL', '313', '419 v West Indies, 15/10/2017']
['58', 'Shikha Pandey', 'IND', '309', '383 v South Africa, 14/10/2019']
['59', 'Murshida Khatun', 'BAN', '300', '308 v Zimbabwe, 15/11/2021']
['60', 'Chedean Nation', 'WI', '293', '314 v Pakistan, 12/07/2021']
['61', 'Lara Goodall', 'SA', '291', '320 v West Indies, 10/09/2021']
['62', 'Kycia Knight', 'WI', '290', '404 v Sri Lanka, 18/05/2015']
['63', 'Fran Wilson', 'ENG', '290', '355 v India, 09/04/2018']
['64', 'Jemimah Rodriques', 'IND', '284', '411 v West Indies, 06/11/2019']
['65', 'Kyshona Knight', 'WI', '284', '379 v Pakistan, 18/07/2021']
['66', 'Nigar Sultana', 'BAN', '283', '336 v Pakistan, 02/11/2019']
['67', 'Shemaine Campbelle', 'WI', '279', '403 v New Zealand, 14/09/2014']
['68', 'Rashada Williams', 'WI', '272', '311 v South Africa, 19/09/2021']
['69', 'Lauren Down', 'NZ', '271', '275 v Australia, 04/04/2021']
['70', 'Priya Punia', 'IND', '270', '305 v South Africa, 17/03/2021']
['71', 'Yastika Bhatia', 'IND', '266', '266 v Australia, 26/09/2021']
['72', 'Sophia Dunkley', 'ENG', '266', '266 v New Zealand, 26/09/2021']
['73\n                                \n\n\n\n\n(1)\nThis player has moved up in the rankings since the previous rankings update', 'Nilakshi Silva', 'SL', '261', '279 v Australia, 07/10/2019']
['74\n                                \n\n\n\n\n(1)\nThis player has moved up in the rankings since the previous rankings update', 'Salma Khatun', 'BAN', '259', '366 v South Africa, 22/09/2013']
['75\n                                \n\n\n\n\n(1)\nThis player has moved up in the rankings since the previous rankings update', 'Rachel Priest', 'NZ', '258', '589 v Sri Lanka, 07/11/2015']
['76\n                                \n\n\n\n\n(1)\nThis player has moved up in the rankings since the previous rankings update', 'Lea Tahuhu', 'NZ', '253', '269 v England, 21/09/2021']
['77\n                                \n\n\n\n\n(2)\nThis player has moved up in the rankings since the previous rankings update', 'Mary Waldron', 'IRE', '248', '248 v Zimbabwe, 07/10/2021']
['78\n                                \n\n\n\n\n(5)\nThis player has moved down in the rankings since the previous rankings update', 'Mary-Anne Musonda', 'ZIM', '242', '290 v Ireland, 11/10/2021']
['79\n                                \n\n\n\n\n(1)\nThis player has moved up in the rankings since the previous rankings update', 'Kate Cross', 'ENG', '241', '244 v New Zealand, 21/09/2021']
['80\n                                \n\n\n\n\n(1)\nThis player has moved up in the rankings since the previous rankings update', 'Hayley Jensen', 'NZ', '240', '271 v England, 23/02/2021']
['81\n                                \n\n\n\n\n(2)\nThis player has moved up in the rankings since the previous rankings update', 'Georgia Wareham', 'AUS', '237', '242 v India, 24/09/2021']
['82\n                                \n\n\n\n\n(2)\nThis player has moved up in the rankings since the previous rankings update', 'Sharmin Supta', 'BAN', '235', '235 v Pakistan, 21/11/2021']
['83\n                                \n\n\n\n\n(1)\nThis player has moved down in the rankings since the previous rankings update', 'Sidra Ameen', 'PAK', '233', '319 v South Africa, 09/05/2019']
['84\n                                \n\n\n\n\n(1)\nThis player has moved up in the rankings since the previous rankings update', 'Ritu Moni', 'BAN', '231', '249 v Ireland, 09/09/2016']
['85\n                                \n\n\n\n\n(1)\nThis player has moved up in the rankings since the previous rankings update', 'Amy Hunter', 'IRE', '228', '242 v Zimbabwe, 11/10/2021']
['86\n                                \n\n\n\n\n(1)\nThis player has moved up in the rankings since the previous rankings update', 'Poonam Yadav', 'IND', '227', '260 v South Africa, 11/10/2019']
['87\n                                \n\n\n\n\n(1)\nThis player has moved up in the rankings since the previous rankings update', 'Richa Ghosh', 'IND', '226', '240 v Australia, 24/09/2021']
['88\n                                \n\n\n\n\n(1)\nThis player has moved up in the rankings since the previous rankings update', 'Avanthika Mendis', 'SL', '226', '408 v India, 21/01/2014']
['89\n                                \n\n\n\n\n(1)\nThis player has moved up in the rankings since the previous rankings update', 'Taniya Bhatia', 'IND', '225', '291 v West Indies, 06/11/2019']
['90\n                                \n\n\n\n\n(12)\nThis player has moved down in the rankings since the previous rankings update', 'Josephine Nkomo', 'ZIM', '221', '267 v Ireland, 11/10/2021']
['91', 'Leigh Kasperek', 'NZ', '221', '259 v South Africa, 25/01/2020']
['92', 'Eimear Richardson', 'IRE', '217', '275 v Pakistan, 19/07/2013']
['93', 'Anya Shrubsole', 'ENG', '213', '249 v West Indies, 09/06/2019']
['94', 'Anne Bosch', 'SA', '212', '234 v India, 17/03/2021']
['95', 'Rajeshwari Gayakwad', 'IND', '212', '229 v South Africa, 14/03/2021']
['96', 'Pooja Vastrakar', 'IND', '211', '223 v Australia, 15/03/2018']
['97', 'Anushka Sanjeewani', 'SL', '211', '222 v Australia, 07/10/2019']
['98', 'Tazmin Brits', 'SA', '208', '208 v West Indies, 19/09/2021']
['99', 'Shauna Kavanagh', 'IRE', '207', '218 v Zimbabwe, 11/10/2021']
['100', 'Jess Kerr', 'NZ', '206', '210 v England, 23/09/2021']
---------------------------------------------------------------------------------
(C) Top 10 women’s ODI all-rounder along with the records of their team and rating.
---------------------------------------------------------------------------------
['Pos', 'Player', 'Team', 'Rating', 'Career Best Rating']
['1', 'Marizanne Kapp', 'SA']
['2', 'Natalie Sciver', 'ENG', '372', '391 v New Zealand, 16/09/2021']
['3', 'Ellyse Perry', 'AUS', '365', '548 v West Indies, 11/09/2019']
['4', 'Stafanie Taylor', 'WI', '319', '559 v New Zealand, 10/10/2013']
['5', 'Deepti Sharma', 'IND', '299', '397 v South Africa, 09/10/2019']
['6', 'Ashleigh Gardner', 'AUS', '275', '275 v India, 26/09/2021']
['7', 'Dane van Niekerk', 'SA', '274', '421 v Sri Lanka, 11/02/2019']
['8', 'Hayley Matthews', 'WI', '272', '272 v Ireland, 23/11/2021']
['9', 'Jess Jonassen', 'AUS', '272', '308 v West Indies, 11/09/2019']
['10', 'Katherine Brunt', 'ENG', '272', '295 v New Zealand, 21/09/2021']
['11', 'Jhulan Goswami', 'IND', '251', '308 v Australia, 02/02/2016']
['12', 'Sophie Devine', 'NZ', '248', '305 v Australia, 05/10/2020']
['13', 'Rumana Ahmed', 'BAN', '195', '195 v Pakistan, 21/11/2021']
['14', 'Heather Knight', 'ENG', '195', '249 v West Indies, 13/06/2019']
['15', 'Amelia Kerr', 'NZ', '193', '247 v Australia, 07/04/2021']
['16', 'Nida Dar', 'PAK', '186', '189 v Bangladesh, 21/11/2021']
['17', 'Shikha Pandey', 'IND', '173', '262 v South Africa, 14/10/2019']
['18', 'Kate Cross', 'ENG', '141', '141 v New Zealand, 26/09/2021']
['19', 'Lea Tahuhu', 'NZ', '140', '156 v England, 21/09/2021']
['20', 'Chamari Athapaththu', 'SL', '136', '187 v South Africa, 17/02/2019']

# 6) Write a python program to scrape details of all the posts from coreyms.com. Scrape the heading, date, content and the code for the video from the link for the youtube video from the post.

In [5]:
#Solution:

import requests
from bs4 import BeautifulSoup
 
url = 'https://coreyms.com/'
page6=requests.get(url)
#page6
soup6 = BeautifulSoup(page6.content, "html.parser")

print('---------------------------')
print('Heading:')
print('---------------------------')    
heading = soup6.find_all('h2', attrs={'class':'entry-title'})
for hd in heading:
    print(hd.get_text())
    

print('---------------------------')
print('Date:')
print('---------------------------')    
date = soup6.find_all('time', attrs={'class':'entry-time'})
for dt in date:
    print(dt.get_text())
    
    
print('---------------------------')
print('Content:')
print('---------------------------')    
content = soup6.find_all('div', attrs={'class':'entry-content'})
for ct in content:
    print(ct.get_text())
    

print('---------------------------')
print('Code for the video from the link for the youtube video:')
print('---------------------------')
links = soup6.find_all('iframe', attrs={'class':'youtube-player'})
for link in links:
    print(link['src'])

---------------------------
Heading:
---------------------------
Python Tutorial: Zip Files – Creating and Extracting Zip Archives
Python Data Science Tutorial: Analyzing the 2019 Stack Overflow Developer Survey
Python Multiprocessing Tutorial: Run Code in Parallel Using the Multiprocessing Module
Python Threading Tutorial: Run Code Concurrently Using the Threading Module
Update (2019-09-03)
Python Quick Tip: The Difference Between “==” and “is” (Equality vs Identity)
Python Tutorial: Calling External Commands Using the Subprocess Module
Visual Studio Code (Windows) – Setting up a Python Development Environment and Complete Overview
Visual Studio Code (Mac) – Setting up a Python Development Environment and Complete Overview
Clarifying the Issues with Mutable Default Arguments
---------------------------
Date:
---------------------------
November 19, 2019
October 17, 2019
September 21, 2019
September 12, 2019
September 3, 2019
August 6, 2019
July 24, 2019
May 1, 2019
May 1, 2019
April 24, 2019
---------------------------
Content:
---------------------------

In this video, we will be learning how to create and extract zip archives. We will start by using the zipfile module, and then we will see how to do this using the shutil module. We will learn how to do this with single files and directories, as well as learning how to use gzip as well. Let’s get started…



In this Python Programming video, we will be learning how to download and analyze real-world data from the 2019 Stack Overflow Developer Survey. This is terrific practice for anyone getting into the data science field. We will learn different ways to analyze this data and also some best practices. Let’s get started…





In this Python Programming video, we will be learning how to run code in parallel using the multiprocessing module. We will also look at how to process multiple high-resolution images at the same time using a ProcessPoolExecutor from the concurrent.futures module. Let’s get started…





In this Python Programming video, we will be learning how to run threads concurrently using the threading module. We will also look at how to download multiple high-resolution images online using a ThreadPoolExecutor from the concurrent.futures module. Let’s get started…





Hey everyone. I wanted to give you an update on my videos. I will be releasing videos on threading and multiprocessing within the next week. Thanks so much for your patience. I currently have a temporary recording studio setup at my Airbnb that will allow me to record and edit the threading/multiprocessing videos. I am going to be moving into my new house in 10 days and once I have my recording studio setup then you can expect much faster video releases. I really appreciate how patient everyone has been while I go through this move, especially those of you who are contributing monthly through YouTube


In this Python Programming Tutorial, we will be learning the difference between using “==” and the “is” keyword when doing comparisons. The difference between these is that “==” checks to see if values are equal, and the “is” keyword checks their identity, which means it’s going to check if the values are identical in terms of being the same object in memory. We’ll learn more in the video. Let’s get started…





In this Python Programming Tutorial, we will be learning how to run external commands using the subprocess module from the standard library. We will learn how to run commands, capture the output, handle errors, and also how to pipe output into other commands. Let’s get started…





In this Python Programming Tutorial, we will be learning how to set up a Python development environment in VSCode on Windows. VSCode is a very nice free editor for writing Python applications and many developers are now switching over to this editor. In this video, we will learn how to install VSCode, get the Python extension installed, how to change Python interpreters, create virtual environments, format/lint our code, how to use Git within VSCode, how to debug our programs, how unit testing works, and more. We have a lot to cover, so let’s go ahead and get started…
VSCode on MacOS – https://youtu.be/06I63_p-2A4
Timestamps for topics in this tutorial: Installation – 1:13 Python Extension – 5:48 Switching Interpreters – 10:04 Changing Color Themes – 12:35 VSCode Settings – 16:16 Set Default Python – 21:33 Using Virtual Environments – 25:10 IntelliSense – 29:45 Code Formatting – 32:13 Code Linting – 37:06 Code Runner Extension – 39:42 Git Integration – 47:44 Use Different Terminal – 51:07 Debugging – 58:45 Unit Testing – 1:03:25 Zen Mode – 1:09:55





In this Python Programming Tutorial, we will be learning how to set up a Python development environment in VSCode on MacOS. VSCode is a very nice free editor for writing Python applications and many developers are now switching over to this editor. In this video, we will learn how to install VSCode, get the Python extension installed, how to change Python interpreters, create virtual environments, format/lint our code, how to use Git within VSCode, how to debug our programs, how unit testing works, and more. We have a lot to cover, so let’s go ahead and get started…
VSCode on Windows – https://youtu.be/-nh9rCzPJ20
Timestamps for topics in this tutorial: Installation – 1:11 Python Extension – 6:21 Switching Interpreters – 10:16 Changing Color Themes – 13:08 VSCode Settings – 17:12 Set Default Python – 22:24 Using Virtual Environments – 25:52 IntelliSense – 30:28 Code Formatting – 33:08 Code Linting – 38:01 Code Runner Extension – 40:45 Git Integration – 49:05 Debugging – 58:15 Unit Testing – 1:02:38 Zen Mode – 1:10:42





In this Python Programming Tutorial, we will be clarifying the issues with mutable default arguments. We discussed this in my last video titled “5 Common Python Mistakes and How to Fix Them”, but I received many comments from people who were still confused. So we will be doing a deeper dive to explain exactly what is going on here. Let’s get started…




---------------------------
Code for the video from the link for the youtube video:
---------------------------
https://www.youtube.com/embed/z0gguhEmWiY?version=3&rel=1&showsearch=0&showinfo=1&iv_load_policy=1&fs=1&hl=en-US&autohide=2&wmode=transparent
https://www.youtube.com/embed/_P7X8tMplsw?version=3&rel=1&showsearch=0&showinfo=1&iv_load_policy=1&fs=1&hl=en-US&autohide=2&wmode=transparent
https://www.youtube.com/embed/fKl2JW_qrso?version=3&rel=1&showsearch=0&showinfo=1&iv_load_policy=1&fs=1&hl=en-US&autohide=2&wmode=transparent
https://www.youtube.com/embed/IEEhzQoKtQU?version=3&rel=1&showsearch=0&showinfo=1&iv_load_policy=1&fs=1&hl=en-US&autohide=2&wmode=transparent
https://www.youtube.com/embed/mO_dS3rXDIs?version=3&rel=1&showsearch=0&showinfo=1&iv_load_policy=1&fs=1&hl=en-US&autohide=2&wmode=transparent
https://www.youtube.com/embed/2Fp1N6dof0Y?version=3&rel=1&showsearch=0&showinfo=1&iv_load_policy=1&fs=1&hl=en-US&autohide=2&wmode=transparent
https://www.youtube.com/embed/-nh9rCzPJ20?version=3&rel=1&showsearch=0&showinfo=1&iv_load_policy=1&fs=1&hl=en-US&autohide=2&wmode=transparent
https://www.youtube.com/embed/06I63_p-2A4?version=3&rel=1&showsearch=0&showinfo=1&iv_load_policy=1&fs=1&hl=en-US&autohide=2&wmode=transparent
https://www.youtube.com/embed/_JGmemuINww?version=3&rel=1&showsearch=0&showinfo=1&iv_load_policy=1&fs=1&hl=en-US&autohide=2&wmode=transparent

# 7) Write a python program to scrape house details from mentioned URL. It should include house title, location,area, EMI and price from nobroker.in.

In [12]:
#Solution

import requests
from bs4 import BeautifulSoup
import pandas as pd
 
url = 'https://www.nobroker.in/flats-for-sale-in-koramangala_bangalore'
page7=requests.get(url)
#page7
soup7 = BeautifulSoup(page7.content, "html.parser")
 
    
print('---------------------------')
print('House title:')
print('---------------------------')    
h_title = soup7.find_all('h2', attrs={'class':'heading-6 font-semi-bold nb__25Cl7'})
for ht in h_title:
    print(ht.get_text())
    
    
print('---------------------------')
print('Location:')
print('---------------------------')    
h_loc = soup7.find_all('div', attrs={'class':'nb__1EwQz'})
for hl in h_loc:
    print(hl.get_text())
    
    
print('---------------------------')
print('Area:')
print('---------------------------')    
h_area = soup7.find_all('div', attrs={'class':'nb__FfHqA'})
for ha in h_area:
    print(ha.get_text())
    
    
print('---------------------------')
print('EMI:')
print('---------------------------')    
h_emi = soup7.find_all(id="roomType", attrs={'class':'font-semi-bold heading-6'})
for emi in h_emi:
    print(emi.get_text())
    
    
print('---------------------------')
print('Price:')
print('---------------------------')    
h_price = soup7.find_all(id="minDeposit", attrs={'class':'nb__4L90a'})
for price in h_price:
    print(price.get_text())
    

df_house=pd.DataFrame({'House title':h_title, 'Location': h_loc, 'Area':h_area, 'EMI':h_emi, 'Price':h_price})
df_house

---------------------------
House title:
---------------------------
4 BHK Apartment  For Sale  In Prestige Pinewood In Koramangala
2 BHK Flat  For Sale  In Raheja Residency, Koramangala In Koramangala
3 BHK Apartment  For Sale  In Raheja Residency In Koramangala
2 BHK Flat  For Sale  In Raheja Residency In Koramangala
2 BHK Flat  For Sale  In Floriana Estate, Koramangala In Floriana Estates
3 BHK Flat  For Sale  In Lakshmi Nilaya In  Koramangala
4 BHK Flat  For Sale  In Advaitha Aksha In Koramangala
3 BHK Flat  For Sale  In Advaitha Aksha In Koramangala
2 BHK Flat  For Sale  In Aishwarya Apartment , Koramangala In Koramangala 4th Block, Koramangala
4+ BHK Flat  For Sale  In Ejipura
2 BHK Flat  For Sale  In Prestige Pinewood In Koramangala
3 BHK Flat  For Sale  In Prestige Pinewood In Koramangala
4 BHK Flat  For Sale  In Prestige Pinewood In Koramangala
4 BHK Apartment  For Sale  In Sterling Infinia In Koramangala
3 BHK Apartment  For Sale  In Sterling Infinia In Koramangala
3 BHK Apartment  For Sale  In Vars Golden Gables In Ejipura
3 BHK In Independent House  For Sale  In Koramangala
4 BHK Apartment  For Sale  In Advaitha Aksha In Koramangala
3 BHK Flat  For Sale  In Mantri Classic, Koramangala In Koramangala
3 BHK Flat  For Sale  In Bv Apartment In G Corp Residences
2 BHK In Independent House  For Sale  In Koramangala
3 BHK Apartment  For Sale  In Vars Golden Gables In Ejipura
3 BHK Flat  For Sale  In Dsr Orchid Apartment In Koramangala
2 BHK Flat  For Sale  In Sunshine Apartment  In Kormangla
2 BHK Apartment  For Sale  In Raheja Residency In Koramangala
---------------------------
Location:
---------------------------
Prestige Pinewood  6th Cross Rd, S.T. Bed Extension, 1st Block Koramangala, Koramangala, Bengaluru, Karnataka 560034, India
7th Cross Rd, 3rd Block, Koramangala 1A Block, Koramangala 3 Block, Koramangala, Bengaluru, Karnataka 560034, India
Raheja Residency  7th Cross Rd, 3rd Block, Koramangala 1A Block, Koramangala 3 Block, Koramangala, Bengaluru, Karnataka 560034, India
7th Cross Rd, 3rd Block, Koramangala 1A Block, Koramangala 3 Block
Koramangala
S.T. Bed Extension, Near  prestige pinewood
AKSHA Boulevard, 1st East Main Road, No 148, Jakkasandra Ext, Koramangala, Bengaluru, Karnataka 560034, India
AKSHA Boulevard, 1st East Main Road, No 148, Jakkasandra Ext, Koramangala, Bengaluru, Karnataka 560034, India
7th Main Rd, New Friends Colony, S T Bed Layout, Ejipura,
Standalone Building, Buchappa  layout , Near NGV Swimming Pool
6th Cross Rd, S.T. Bed Extension, 1st Block Koramangala, Koramangala, Bengaluru, Karnataka 560034, India
6th Cross Rd, S.T. Bed Extension, 1st Block Koramangala, Koramangala, Bengaluru, Karnataka 560034, India
6th Cross Rd, S.T. Bed Extension, 1st Block Koramangala, Koramangala, Bengaluru, Karnataka 560034, India
Sterling Infinia  Sarjapur Main Rd, Jakkasandra Extension, Koramangala, Bengaluru, Karnataka 560034, India
Sterling Infinia  Sarjapur Main Rd, Jakkasandra Extension, Koramangala, Bengaluru, Karnataka 560034, India
Vars Golden Gables  Vars Golden Gables, 1st A Main, 8th Cross Rd, S.T. Bed, S T Bed Layout, Ejipura, Bengaluru, Karnataka 560095, India
Independent House, Adugodi Main Rd, Koramangala 8th Block near Corporation Bank - Union Bank and Muneshwara Swamy Temple
Advaitha Aksha  AKSHA Boulevard, 1st East Main Road, No 148, Jakkasandra Ext, Koramangala, Bengaluru, Karnataka 560034, India
4th Block, 1st main, 8th Cross, S.T. Bed, Cauvery Colony, Koramangala, Bengaluru, Karnataka 560034, India
Kormangala Jakkasandra extension near by to sony signal
Independent House, KHB Colony,Near union bank of india kormangala branch
Vars Golden Gables  Vars Golden Gables, 1st A Main, 8th Cross Rd, S.T. Bed, S T Bed Layout, Ejipura, Bengaluru, Karnataka 560095, India
 80 Feet Rd near Maharaja Biryani House
near LVR residency
Raheja Residency  7th Cross Rd, 3rd Block, Koramangala 1A Block, Koramangala 3 Block, Koramangala, Bengaluru, Karnataka 560034, India
---------------------------
Area:
---------------------------
3,600 sqft
1,200 sqft
1,350 sqft
1,260 sqft
1,106 sqft
2,200 sqft
2,441 sqft
1,999 sqft
1,100 sqft
6,000 sqft
1,259 sqft
1,866 sqft
2,462 sqft
3,142 sqft
2,439 sqft
1,605 sqft
1,500 sqft
2,450 sqft
2,030 sqft
2,200 sqft
720 sqft
1,650 sqft
1,650 sqft
1,100 sqft
1,250 sqft
---------------------------
EMI:
---------------------------
₹2.75 Lacs/Month
₹63,045/Month
₹74,508/Month
₹74,508/Month
₹56,168/Month
₹1.26 Lacs/Month
₹1.86 Lacs/Month
₹1.56 Lacs/Month
₹51,583/Month
₹1.09 Lacs/Month
₹1 Lacs/Month
₹1.48 Lacs/Month
₹1.94 Lacs/Month
₹2.34 Lacs/Month
₹1.82 Lacs/Month
₹74,508/Month
₹65,911/Month
₹2.87 Lacs/Month
₹1.38 Lacs/Month
₹1.32 Lacs/Month
₹75,655/Month
₹65,911/Month
₹68,777/Month
₹46,997/Month
₹74,508/Month
---------------------------
Price:
---------------------------
₹4.8 Crores₹13,333 per sq.ft.
₹1.1 Crores₹9,167 per sq.ft.
₹1.3 Crores₹9,630 per sq.ft.
₹1.3 Crores₹10,317 per sq.ft.
₹98 Lacs₹8,861 per sq.ft.
₹2.2 Crores₹10,000 per sq.ft.
₹3.25 Crores₹13,314 per sq.ft.
₹2.73 Crores₹13,657 per sq.ft.
₹90 Lacs₹8,182 per sq.ft.
₹1.9 Crores₹3,167 per sq.ft.
₹1.75 Crores₹13,900 per sq.ft.
₹2.58 Crores₹13,826 per sq.ft.
₹3.39 Crores₹13,769 per sq.ft.
₹4.09 Crores₹13,017 per sq.ft.
₹3.18 Crores₹13,038 per sq.ft.
₹1.3 Crores₹8,100 per sq.ft.
₹1.15 Crores₹7,667 per sq.ft.
₹5 Crores₹20,408 per sq.ft.
₹2.4 Crores₹11,823 per sq.ft.
₹2.3 Crores₹10,455 per sq.ft.
₹1.32 Crores₹18,333 per sq.ft.
₹1.15 Crores₹6,970 per sq.ft.
₹1.2 Crores₹7,273 per sq.ft.
₹82 Lacs₹7,455 per sq.ft.
₹1.3 Crores₹10,400 per sq.ft.

,House title,Location,Area,EMI,Price
0,[[4 BHK Apartment For Sale In Prestige Pinew...,"[[Prestige Pinewood], , , 6th Cross Rd, S.T...","[3,600 sqft]","[[₹], 2.75 Lacs/Month]","[[[], [₹, , 4.8 Crores]], [₹13,333 per sq.ft.]]"
1,"[[2 BHK Flat For Sale In Raheja Residency, K...","[7th Cross Rd, 3rd Block, Koramangala 1A Block...","[1,200 sqft]","[[₹], 63,045/Month]","[[[], [₹, , 1.1 Crores]], [₹9,167 per sq.ft.]]"
2,[[3 BHK Apartment For Sale In Raheja Residen...,"[[Raheja Residency], , , 7th Cross Rd, 3rd ...","[1,350 sqft]","[[₹], 74,508/Month]","[[[], [₹, , 1.3 Crores]], [₹9,630 per sq.ft.]]"
3,[[2 BHK Flat For Sale In Raheja Residency In...,"[7th Cross Rd, 3rd Block, Koramangala 1A Block...","[1,260 sqft]","[[₹], 74,508/Month]","[[[], [₹, , 1.3 Crores]], [₹10,317 per sq.ft.]]"
4,"[[2 BHK Flat For Sale In Floriana Estate, Ko...",[Koramangala],"[1,106 sqft]","[[₹], 56,168/Month]","[[[], [₹, , 98 Lacs]], [₹8,861 per sq.ft.]]"
5,[[3 BHK Flat For Sale In Lakshmi Nilaya In ...,"[S.T. Bed Extension, Near prestige pinewood]","[2,200 sqft]","[[₹], 1.26 Lacs/Month]","[[[], [₹, , 2.2 Crores]], [₹10,000 per sq.ft.]]"
6,[[4 BHK Flat For Sale In Advaitha Aksha In K...,"[AKSHA Boulevard, 1st East Main Road, No 148, ...","[2,441 sqft]","[[₹], 1.86 Lacs/Month]","[[[], [₹, , 3.25 Crores]], [₹13,314 per sq.ft.]]"
7,[[3 BHK Flat For Sale In Advaitha Aksha In K...,"[AKSHA Boulevard, 1st East Main Road, No 148, ...","[1,999 sqft]","[[₹], 1.56 Lacs/Month]","[[[], [₹, , 2.73 Crores]], [₹13,657 per sq.ft.]]"
8,[[2 BHK Flat For Sale In Aishwarya Apartment...,"[7th Main Rd, New Friends Colony, S T Bed Layo...","[1,100 sqft]","[[₹], 51,583/Month]","[[[], [₹, , 90 Lacs]], [₹8,182 per sq.ft.]]"
9,"[[4+ BHK Flat For Sale In Ejipura], , [[]]]","[Standalone Building, Buchappa layout , Near ...","[6,000 sqft]","[[₹], 1.09 Lacs/Month]","[[[], [₹, , 1.9 Crores]], [₹3,167 per sq.ft.]]"
10,[[2 BHK Flat For Sale In Prestige Pinewood I...,"[6th Cross Rd, S.T. Bed Extension, 1st Block K...","[1,259 sqft]","[[₹], 1 Lacs/Month]","[[[], [₹, , 1.75 Crores]], [₹13,900 per sq.ft.]]"
11,[[3 BHK Flat For Sale In Prestige Pinewood I...,"[6th Cross Rd, S.T. Bed Extension, 1st Block K...","[1,866 sqft]","[[₹], 1.48 Lacs/Month]","[[[], [₹, , 2.58 Crores]], [₹13,826 per sq.ft.]]"
12,[[4 BHK Flat For Sale In Prestige Pinewood I...,"[6th Cross Rd, S.T. Bed Extension, 1st Block K...","[2,462 sqft]","[[₹], 1.94 Lacs/Month]","[[[], [₹, , 3.39 Crores]], [₹13,769 per sq.ft.]]"
13,[[4 BHK Apartment For Sale In Sterling Infin...,"[[Sterling Infinia], , , Sarjapur Main Rd, ...","[3,142 sqft]","[[₹], 2.34 Lacs/Month]","[[[], [₹, , 4.09 Crores]], [₹13,017 per sq.ft.]]"
14,[[3 BHK Apartment For Sale In Sterling Infin...,"[[Sterling Infinia], , , Sarjapur Main Rd, ...","[2,439 sqft]","[[₹], 1.82 Lacs/Month]","[[[], [₹, , 3.18 Crores]], [₹13,038 per sq.ft.]]"
15,[[3 BHK Apartment For Sale In Vars Golden Ga...,"[[Vars Golden Gables], , , Vars Golden Gabl...","[1,605 sqft]","[[₹], 74,508/Month]","[[[], [₹, , 1.3 Crores]], [₹8,100 per sq.ft.]]"
16,[[3 BHK In Independent House For Sale In Kor...,"[Independent House, Adugodi Main Rd, Koramanga...","[1,500 sqft]","[[₹], 65,911/Month]","[[[], [₹, , 1.15 Crores]], [₹7,667 per sq.ft.]]"
17,[[4 BHK Apartment For Sale In Advaitha Aksha...,"[[Advaitha Aksha], , , AKSHA Boulevard, 1st...","[2,450 sqft]","[[₹], 2.87 Lacs/Month]","[[[], [₹, , 5 Crores]], [₹20,408 per sq.ft.]]"
18,"[[3 BHK Flat For Sale In Mantri Classic, Kor...","[4th Block, 1st main, 8th Cross, S.T. Bed, Cau...","[2,030 sqft]","[[₹], 1.38 Lacs/Month]","[[[], [₹, , 2.4 Crores]], [₹11,823 per sq.ft.]]"
19,[[3 BHK Flat For Sale In Bv Apartment In G C...,[Kormangala Jakkasandra extension near by to s...,"[2,200 sqft]","[[₹], 1.32 Lacs/Month]","[[[], [₹, , 2.3 Crores]], [₹10,455 per sq.ft.]]"
20,[[2 BHK In Independent House For Sale In Kor...,"[Independent House, KHB Colony,Near union bank...",[720 sqft],"[[₹], 75,655/Month]","[[[], [₹, , 1.32 Crores]], [₹18,333 per sq.ft.]]"
21,[[3 BHK Apartment For Sale In Vars Golden Ga...,"[[Vars Golden Gables], , , Vars Golden Gabl...","[1,650 sqft]","[[₹], 65,911/Month]","[[[], [₹, , 1.15 Crores]], [₹6,970 per sq.ft.]]"
22,[[3 BHK Flat For Sale In Dsr Orchid Apartmen...,[ 80 Feet Rd near Maharaja Biryani House],"[1,650 sqft]","[[₹], 68,777/Month]","[[[], [₹, , 1.2 Crores]], [₹7,273 per sq.ft.]]"
23,[[2 BHK Flat For Sale In Sunshine Apartment ...,[near LVR residency],"[1,100 sqft]","[[₹], 46,997/Month]","[[[], [₹, , 82 Lacs]], [₹7,455 per sq.ft.]]"
24,[[2 BHK Apartment For Sale In Raheja Residen...,"[[Raheja Residency], , , 7th Cross Rd, 3rd ...","[1,250 sqft]","[[₹], 74,508/Month]","[[[], [₹, , 1.3 Crores]], [₹10,400 per sq.ft.]]"

# 8) Write a python program to scrape mentioned details from dineout.co.in :     (i) Restaurant name (ii) Cuisine (iii) Location (iv) Ratings (v) Image URL

In [2]:
#Solution

import pandas as pd
import requests
from bs4 import BeautifulSoup
 
url = 'https://www.dineout.co.in/delhi-restaurants/'
page8=requests.get(url)
#page8 
soup8 = BeautifulSoup(page8.content, "html.parser")
 
    
print('---------------------------')
print('(i) Restaurant name:')
print('---------------------------')    
res = soup8.find_all('div', attrs={'class':'restnt-info cursor'})
for rn in res:
    print(rn.get_text())
 

print('---------------------------')
print('(ii) Cuisine:')
print('---------------------------')
cns = soup8.find_all('span', class_="double-line-ellipsis") 
for c in cns:
    print(c.text.split('|')[1])
    
           
print('---------------------------')
print('(iii) Location:')
print('---------------------------')    
loc = soup8.find_all('div', attrs={'class':'restnt-loc ellipsis'})
for l in loc:
    print(l.get_text())

    
print('---------------------------')
print('(iv) Ratings:')
print('---------------------------')    
rate = soup8.find_all('div', attrs={'class':'restnt-rating rating-4'})
for rt in rate:
    print(rt.get_text())
    
    
      
print('---------------------------')
print('image URL')
print('---------------------------')
pics = soup8.find_all('img',attrs={'class':'no-img'})
for img in pics:
    print(img['data-src']) 
    
    

df_Restaurant=pd.DataFrame({'Restaurant name':res, 'Cuisine':cns, 'Location':loc, 'Ratings':rate, 'image URL':pics})
df_Restaurant

---------------------------
(i) Restaurant name:
---------------------------
LocalScindia House,Connaught Place, Central Delhi
TamashaConnaught Place, Central Delhi
The G.T. ROADM-Block,Connaught Place, Central Delhi
Unplugged CourtyardConnaught Place, Central Delhi
PadmanabhamJanpath, Central Delhi
Ministry Of BeerM-Block,Connaught Place, Central Delhi
Connaught Clubhouse MicrobreweryJanpath, Central Delhi
The Junkyard CafeConnaught Place, Central Delhi
Out Of The Box CourtyardConnaught Place, Central Delhi
38 BarracksM-Block,Connaught Place, Central Delhi
QBAConnaught Place, Central Delhi
SandozConnaught Place, Central Delhi
Ardor 2.1 Restaurant and LoungeConnaught Place, Central Delhi
My Bar SquareConnaught Place, Central Delhi
TamraShangri La Eros New Delhi,Janpath, Central Delhi
Chili's American Grill and BarM-Block,Connaught Place, Central Delhi
Farzi CafeConnaught Place, Central Delhi
Station BarF-Block,Connaught Place, Central Delhi
The Darzi Bar & KitchenConnaught Place, Central Delhi
The Luggage Room By SandozM-Block,Connaught Place, Central Delhi
Lazeez AffaireConnaught Place, Central Delhi
---------------------------
(ii) Cuisine:
---------------------------
 Continental, Italian, North Indian, Asian, Fast Food
 Continental, Finger Food, Asian, Italian, North Indian
 North Indian
 North Indian, Continental
 South Indian, North Indian, Street Food
 Finger Food, North Indian, Italian, Continental, Asian, Oriental , Fusion
 Multi-Cuisine, Asian, Italian, Mexican
 Asian, Mediterranean, North Indian, Italian, Oriental
 Multi-Cuisine, American, Asian, Chinese, Continental, Fast Food, Italian, North Indian, Pizza
 North Indian, Chinese, Continental, Italian
 Multi-Cuisine, Continental, Italian, North Indian, Oriental
 North Indian, Chinese, Mughlai
 Multi-Cuisine, Chinese, Continental, Italian, North Indian, Seafood
 Finger Food, Chinese, Continental, Italian
 Multi-Cuisine, North Indian, Japanese, European, Oriental
 Mexican, American, Italian
 Modern Indian, Continental, Finger Food
 Multi-Cuisine, North Indian, Italian, Continental, Mediterranean, Oriental
 Multi-Cuisine, Asian, Continental, European, Italian, Mexican, North Indian, Oriental
 Multi-Cuisine, North Indian, Italian, Chinese, Continental
 North Indian, Mughlai
---------------------------
(iii) Location:
---------------------------
Scindia House,Connaught Place, Central Delhi
Connaught Place, Central Delhi
M-Block,Connaught Place, Central Delhi
Connaught Place, Central Delhi
Janpath, Central Delhi
M-Block,Connaught Place, Central Delhi
Janpath, Central Delhi
Connaught Place, Central Delhi
Connaught Place, Central Delhi
M-Block,Connaught Place, Central Delhi
Connaught Place, Central Delhi
Connaught Place, Central Delhi
Connaught Place, Central Delhi
Connaught Place, Central Delhi
Shangri La Eros New Delhi,Janpath, Central Delhi
M-Block,Connaught Place, Central Delhi
Connaught Place, Central Delhi
F-Block,Connaught Place, Central Delhi
Connaught Place, Central Delhi
M-Block,Connaught Place, Central Delhi
Connaught Place, Central Delhi
---------------------------
(iv) Ratings:
---------------------------
4
4.2
4.3
4.1
4.2
4
4.1
4.1
4.1
4.3
4.3
4.1
3.9
3.8
4.4
4.4
4.2
4.1
4.1
4
4.2
---------------------------
image URL
---------------------------
https://im1.dineout.co.in/images/uploads/restaurant/sharpen/2/b/t/p27452-15020105505986dcb6d147f.jpg?tr=tr:n-medium
https://im1.dineout.co.in/images/uploads/restaurant/sharpen/2/a/j/p20996-145631488756cd9a0796608.jpg?tr=tr:n-medium
https://im1.dineout.co.in/images/uploads/restaurant/sharpen/3/z/j/p31393-15972091445f337a38df16d.jpg?tr=tr:n-medium
https://im1.dineout.co.in/images/uploads/restaurant/sharpen/2/u/y/p20941-15700828565d959028e9f28.jpg?tr=tr:n-medium
https://im1.dineout.co.in/images/uploads/restaurant/sharpen/7/t/r/p76678-15980881015f40e3a588f73.jpg?tr=tr:n-medium
https://im1.dineout.co.in/images/uploads/restaurant/sharpen/3/a/d/p32381-1495943585592a49a166fe7.jpg?tr=tr:n-medium
https://im1.dineout.co.in/images/uploads/restaurant/sharpen/7/c/z/p77626-15833232035e5f98437554f.jpg?tr=tr:n-medium
https://im1.dineout.co.in/images/uploads/restaurant/sharpen/2/e/p/p20298-1484731590587f34c63a2a1.jpg?tr=tr:n-medium
https://im1.dineout.co.in/images/uploads/restaurant/sharpen/8/x/t/p83921-16017104805f782990b9b0c.jpg?tr=tr:n-medium
https://im1.dineout.co.in/images/uploads/restaurant/sharpen/2/y/q/p21171-1631359509613c92152f775.jpg?tr=tr:n-medium
https://im1.dineout.co.in/images/uploads/restaurant/sharpen/2/e/e/p29906-16183962346076c44ac433d.jpg?tr=tr:n-medium
https://im1.dineout.co.in/images/uploads/restaurant/sharpen/8/v/r/p80493-16064603445fc0a3b8c5926.jpg?tr=tr:n-medium
https://im1.dineout.co.in/images/uploads/restaurant/sharpen/2/a/s/p221-15968682845f2e46bc185f1.jpg?tr=tr:n-medium
https://im1.dineout.co.in/images/uploads/restaurant/sharpen/1/x/q/p12709-15681189455d7798a1df342.jpg?tr=tr:n-medium
https://im1.dineout.co.in/images/uploads/restaurant/sharpen/1/y/t/p19271-15566180735cc81b596637a.jpg?tr=tr:n-medium
https://im1.dineout.co.in/images/uploads/restaurant/sharpen/3/h/k/p31397-150417909459a7f3967dace.jpg?tr=tr:n-medium
https://im1.dineout.co.in/images/uploads/restaurant/sharpen/4/k/m/p4199-16098546105ff46e92bab5b.jpg?tr=tr:n-medium
https://im1.dineout.co.in/images/uploads/restaurant/sharpen/9/d/t/p971-15465830125c2efbe4260ab.jpg?tr=tr:n-medium
https://im1.dineout.co.in/images/uploads/restaurant/sharpen/3/n/t/p30606-15820047025e4b79ded3e7c.jpg?tr=tr:n-medium
https://im1.dineout.co.in/images/uploads/restaurant/sharpen/2/b/u/p23048-1477373818580eef7a04d08.jpg?tr=tr:n-medium
https://im1.dineout.co.in/images/uploads/restaurant/sharpen/3/v/k/p34582-15129702825a2e182a631e4.jpg?tr=tr:n-medium

,Restaurant name,Cuisine,Location,Ratings,image URL
0,"[[Local], [[Scindia House,], [Connaught Place]...","[[₹ 1,800 for 2 (approx)], [ | ], [Continental...","[[Scindia House,], [Connaught Place], , , [Cen...",[4],[]
1,"[[Tamasha], [[Connaught Place], , , [Central D...","[[₹ 2,000 for 2 (approx)], [ | ], [Continental...","[[Connaught Place], , , [Central Delhi]]",[4.2],[]
2,"[[The G.T. ROAD], [[M-Block,], [Connaught Plac...","[[₹ 1,800 for 2 (approx)], [ | ], [North Indian]]","[[M-Block,], [Connaught Place], , , [Central D...",[4.3],[]
3,"[[Unplugged Courtyard], [[Connaught Place], , ...","[[₹ 2,000 for 2 (approx)], [ | ], [North India...","[[Connaught Place], , , [Central Delhi]]",[4.1],[]
4,"[[Padmanabham], [[Janpath], , , [Central Delhi]]]","[[₹ 700 for 2 (approx)], [ | ], [South Indian]...","[[Janpath], , , [Central Delhi]]",[4.2],[]
5,"[[Ministry Of Beer], [[M-Block,], [Connaught P...","[[₹ 2,100 for 2 (approx)], [ | ], [Finger Food...","[[M-Block,], [Connaught Place], , , [Central D...",[4],[]
6,"[[Connaught Clubhouse Microbrewery], [[Janpath...","[[₹ 2,000 for 2 (approx)], [ | ], [Multi-Cuisi...","[[Janpath], , , [Central Delhi]]",[4.1],[]
7,"[[The Junkyard Cafe], [[Connaught Place], , , ...","[[₹ 1,800 for 2 (approx)], [ | ], [Asian], [, ...","[[Connaught Place], , , [Central Delhi]]",[4.1],[]
8,"[[Out Of The Box Courtyard], [[Connaught Place...","[[₹ 2,000 for 2 (approx)], [ | ], [Multi-Cuisi...","[[Connaught Place], , , [Central Delhi]]",[4.1],[]
9,"[[38 Barracks], [[M-Block,], [Connaught Place]...","[[₹ 2,000 for 2 (approx)], [ | ], [North India...","[[M-Block,], [Connaught Place], , , [Central D...",[4.3],[]
10,"[[QBA], [[Connaught Place], , , [Central Delhi]]]","[[₹ 2,100 for 2 (approx)], [ | ], [Multi-Cuisi...","[[Connaught Place], , , [Central Delhi]]",[4.3],[]
11,"[[Sandoz], [[Connaught Place], , , [Central De...","[[₹ 1,100 for 2 (approx)], [ | ], [North India...","[[Connaught Place], , , [Central Delhi]]",[4.1],[]
12,"[[Ardor 2.1 Restaurant and Lounge], [[Connaugh...","[[₹ 2,000 for 2 (approx)], [ | ], [Multi-Cuisi...","[[Connaught Place], , , [Central Delhi]]",[3.9],[]
13,"[[My Bar Square], [[Connaught Place], , , [Cen...","[[₹ 1,500 for 2 (approx)], [ | ], [Finger Food...","[[Connaught Place], , , [Central Delhi]]",[3.8],[]
14,"[[Tamra], [[Shangri La Eros New Delhi,], [Janp...","[[₹ 4,000 for 2 (approx)], [ | ], [Multi-Cuisi...","[[Shangri La Eros New Delhi,], [Janpath], , , ...",[4.4],[]
15,"[[Chili's American Grill and Bar], [[M-Block,]...","[[₹ 2,000 for 2 (approx)], [ | ], [Mexican], [...","[[M-Block,], [Connaught Place], , , [Central D...",[4.4],[]
16,"[[Farzi Cafe], [[Connaught Place], , , [Centra...","[[₹ 2,000 for 2 (approx)], [ | ], [Modern Indi...","[[Connaught Place], , , [Central Delhi]]",[4.2],[]
17,"[[Station Bar], [[F-Block,], [Connaught Place]...","[[₹ 2,000 for 2 (approx)], [ | ], [Multi-Cuisi...","[[F-Block,], [Connaught Place], , , [Central D...",[4.1],[]
18,"[[The Darzi Bar & Kitchen], [[Connaught Place]...","[[₹ 2,000 for 2 (approx)], [ | ], [Multi-Cuisi...","[[Connaught Place], , , [Central Delhi]]",[4.1],[]
19,"[[The Luggage Room By Sandoz], [[M-Block,], [C...","[[₹ 1,800 for 2 (approx)], [ | ], [Multi-Cuisi...","[[M-Block,], [Connaught Place], , , [Central D...",[4],[]
20,"[[Lazeez Affaire], [[Connaught Place], , , [Ce...","[[₹ 2,600 for 2 (approx)], [ | ], [North India...","[[Connaught Place], , , [Central Delhi]]",[4.2],[]

# 9) Write a python program to scrape weather details for last 24 hours from Tutiempo.net :
i) Hour
ii) Temperature
iii) Wind
iv) Weather condition
v) Humidity
vi) Pressure

In [1]:
# Solution 

import requests
from bs4 import BeautifulSoup

page9=requests.get('https://en.tutiempo.net/delhi.html?data=last-24-hours')
# page9

soup9 = BeautifulSoup(page9.content, "html.parser")
    
# print('---------------------------')
# print('(i)Hour:')
# print('---------------------------')    
# hrs =[] 
# for td in soup9.find_all('tr'):
#         hrs.append(td.text.replace('\n',' '))
#         print(hrs)

print('---------------------------')
print('(ii) Temperature:')
print('---------------------------')    
temp = soup9.find_all(attrs={'class':'t Temp'})
for t in temp:
    print(t.get_text())

    
print('---------------------------')
print('(iii) Wind:')
print('---------------------------')    
wind = soup9.findAll(attrs={'class':'wind'}) 
for w in wind:
    print(w.get_text())

print('---------------------------')
print('(iv) Weather condition:')
print('---------------------------')
WC1 = soup9.find_all('span', class_='thhip ico i0530 u3012n') 
for wc in WC1:
    print(wc.get_text())
    
WC2 = soup9.find_all('span', class_='thhip ico i0530 u303') 
for wc2 in WC2:
    print(wc2.get_text())
    
WC3 = soup9.find_all('span', class_='thhip ico i0530 u3018') 
for wc3 in WC3:
    print(wc3.get_text())
       

print('---------------------------')
print(' (v)Humidity:')
print('---------------------------')    
Humidity = soup9.find_all(attrs={'class':'hr'}) 
for h in Humidity:
    print(h.get_text())
    
    
print('---------------------------')
print('(vi) Pressure:')
print('---------------------------')    
Pressure = soup9.find_all(attrs={'class':'prob'})
for p in Pressure:
    print(p.get_text())

---------------------------
(ii) Temperature:
---------------------------
15°C
15°C
16°C
16°C
16°C
16°C
16°C
16°C
16°C
16°C
16°C
16°C
16°C
16°C
16°C
17°C
17°C
17°C
17°C
18°C
18°C
19°C
18°C
19°C
19°C
18°C
18°C
18°C
18°C
17°C
17°C
16°C
16°C
15°C
15°C
15°C
15°C
15°C
15°C
15°C
16°C
16°C
16°C
16°C
16°C
16°C
16°C
17°C
17°C
17°C
---------------------------
(iii) Wind:
---------------------------
Calm
6 km/h
6 km/h
6 km/h
6 km/h
6 km/h
6 km/h
6 km/h
6 km/h
11 km/h
6 km/h
7 km/h
6 km/h
6 km/h
6 km/h
11 km/h
13 km/h
11 km/h
7 km/h
7 km/h
7 km/h
9 km/h
9 km/h
9 km/h
9 km/h
9 km/h
7 km/h
7 km/h
9 km/h
7 km/h
7 km/h
7 km/h
7 km/h
Calm
6 km/h
9 km/h
6 km/h
7 km/h
6 km/h
6 km/h
7 km/h
6 km/h
6 km/h
6 km/h
6 km/h
6 km/h
6 km/h
Calm
Calm
Calm
---------------------------
(iv) Weather condition:
---------------------------
Mist
Mist
Mist
Mist
Mist
Mist
Mist
Fog
Fog
Fog
Fog
Fog
Fog
Drizzle
Drizzle
Drizzle
Drizzle
Light Rain
Light Rain
Light Rain
Light Rain
Light Rain
Drizzle
Light Rain
Light Rain
Light Rain
Light Rain
Drizzle
Drizzle
Drizzle
Light Rain
Light Rain
---------------------------
 (v)Humidity:
---------------------------
94%
100%
94%
94%
100%
100%
100%
100%
100%
100%
100%
100%
100%
100%
100%
94%
100%
100%
100%
94%
88%
83%
83%
78%
78%
83%
88%
88%
88%
82%
82%
88%
88%
88%
88%
88%
88%
88%
88%
88%
82%
82%
82%
82%
82%
82%
82%
82%
82%
82%
---------------------------
(vi) Pressure:
---------------------------
1017 hPa
1017 hPa
1017 hPa
1017 hPa
1018 hPa
1018 hPa
1018 hPa
1018 hPa
1017 hPa
1017 hPa
1018 hPa
1018 hPa
1017 hPa
1017 hPa
1017 hPa
1018 hPa
1018 hPa
1017 hPa
1017 hPa
- hPa
- hPa
1017 hPa
1017 hPa
1017 hPa
1018 hPa
1018 hPa
1019 hPa
1019 hPa
1020 hPa
1020 hPa
1020 hPa
1019 hPa
1019 hPa
1018 hPa
1018 hPa
1018 hPa
1017 hPa
1017 hPa
1016 hPa
1016 hPa
1016 hPa
1016 hPa
1016 hPa
1016 hPa
1017 hPa
1017 hPa
1017 hPa
1017 hPa
1017 hPa
1017 hPa

# 10) Write a python program to scrape monument name, monument description, image URL about top 10 monuments from puredestinations.co.uk.

In [11]:
# Solution 10

import requests
from bs4 import BeautifulSoup

url = 'https://www.puredestinations.co.uk/top-10-famous-monuments-to-visit-in-india/'
page10=requests.get(url)
#page10
soup10 = BeautifulSoup(page10.content, "html.parser")

print('---------------------------')
print('Monument name:')
print('---------------------------')
#monument name:
monument_name = soup10.find_all('strong')
for i in monument_name:
    print(i.get_text())

    
print('---------------------------')
print('Monument description:')
print('---------------------------')
monument_description = soup10.find_all('p')
for j in monument_description:
    print(j.get_text())

    
print('---------------------------')
print('image URL')
print('---------------------------')    
images = soup10.find_all('img')
for k in images:
     print(k['src'].replace('data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==', ' ').replace('&noscript=1', ' '))

---------------------------
Monument name:
---------------------------
Taj Mahal, Agra
Golden Temple (Harmandir Sahib), Amritsar
Meenakshi Temple, Madurai
Mysore Palace, Mysore
Gateway of India, Mumbai
Red Fort, New Delhi
Hawa Mahal, Jaipur
Qutub Minar, New Delhi
Sanchi Stupa, Sanchi
Charminar, Hyderabad
Things to know before planning your trip to India
---------------------------
Monument description:
---------------------------
Add items to your wishlist to see them here.
Add items to your wishlist to see them here.
Call us now
Rich in culture and diversity, India is home to some of the finest historical monuments in the world. Most recognised by the UNESCO World Heritage Site, the famous Indian monuments include the beautiful Taj Mahal, the sacred Golden Temple and the cultural site, Hawa Mahal. Discover and experience the magnificent insights into India’s rich heritage and ancient architecture. Read on for our list of the top must see historical monuments in India below.
Taj Mahal, Agra
Enlisted in the Seven Wonders of the World, The Taj Mahal is one of the most beautiful and famous buildings located in the city of Agra. This white marble monument was built by a Mughal Emperor called Shahajahan in memory of his beloved wife. Due to its amazing architecture and the history behind it, this world heritage site has become very popular to visit by all travellers and romantics from all over the world.

Golden Temple (Harmandir Sahib), Amritsar
The holiest shrine and pilgrimage place located in Amritsar is The Golden Temple known as the Harmandir Sahib. This is the most famous and sacred Sikh Gurdwara in Punjab, India, adorned with rich history and gold gilded exterior. If you are interested in culture and history, be sure to visit this popular attraction in India.

Meenakshi Temple, Madurai
Meenakshi Temple is situated on the Southern banks of Vaigai River in the temple city Madurai. This temple is dedicated to Parvati and her consort, Shiva and is visited by most Hindu and Tamil devotees and architectural lovers throughout the world. It is believed that this shrine houses 33,000 sculptures in its 14 gopurams. It’s no doubt one place to visit if you are impressed with art and cultural history.

Mysore Palace, Mysore
The Mysore Palace is a famous historical monument in the city of Mysore in Karnataka. Commonly described as the City of Palaces, this is the most famous tourist attraction in India after the Taj Mahal. It is a sight not be missed with its spacious halls, lovely art paintings and Indo-Saracenic style architecture. Best time to visit is at night due to the astonishing illuminated lights covering the whole monument.

Gateway of India, Mumbai
Even though Mumbai is famous for its Bollywood actors and movies, the most famous attraction in Mumbai is The Gateway of India. It is a popular gathering spot for locals, travellers, street vendors and photographers and is known as the Taj Mahal of Mumbai. The majestic monument was built to commemorate the visit of King George V and Queen Mary to Bombay. With so much fun and excitement this place is not to be missed with family or on your tour of India.

Red Fort, New Delhi
Declared as the UNESCO’s World Heritage Site, Red Fort is located in the centre of beautiful Delhi. If you love learning about history and culture then this famous historic monument is a must see place to visit. Built by the Mughal Emperor, Shah Jahan in 1648, and housing a number of museums, its walls are built of red sandstone. The best time to visit is on Independence Day where the Prime Minister of India hoists the national flag at the Red Fort. End the day by heading to an Indian restaurant and enjoy the varieties of wonderful cuisines.

Hawa Mahal, Jaipur
Explore a blend of beauty and Rajasthan culture, the Hawa Mahal also known as Palace of Winds is situated in the capital of Rajasthan, Jaipur. Built from red and pink sandstones by the Maharaja Sawi Pratap Singh in 1799, this unique five storey structure is one of the most prominent tourist attractions in the Jaipur city.

Qutub Minar, New Delhi
Discover one of the tallest towers in the world and the second tallest Minar of India standing elegantly in the Capital city, New Delhi. Standing at 72.5 metres and consisting of around 379 stairs, this famous monument represents the rich architecture of India. As it is a UNESCO World Heritage Site made of red sandstone and decorated with Arabic and Brahmi inscriptions, travellers from around the world come to view this most famous tower in India.

Sanchi Stupa, Sanchi
The beautiful and massive dome, Sanchi Stupa also known as the Great Stupa is a world renowned Buddhist monument in Sanchi, India. It was constructed by Emperor Ashoka, and is one of the oldest stone structures in the heart of India. Experience the Indian culture by visiting these major attractions in Sanchi including a number of Buddhist Stupas, monasteries and temples.

Charminar, Hyderabad
No visit to Hyderabad should be complete without visiting the most famous and majestic monument known as the Charminar. This magnificent and striking mosque constructed in 1591 has four minarets and is the most recognisable symbol in the city of Hyderabad.

Things to know before planning your trip to India
Are you inspired to plan an incredible trip to India? Get in touch with Pure Destinations today to speak to a travel expert to plan a tailor made itinerary. Fancy exploring these famous monuments in India? Why not contact us today!
Speak To Our Travel Experts
Get A Quote From The Experts
Find Out About Our Luxury Service
Keep up to date with all our exclusive offers, and the best inspiration and advice with by joining our mailing list.
Where to go. What to do. Check out all the latest hotspots by clicking here on use the button below to get a copy sent to your door.
© 2021 Pure Destinations Ltd | Honeymoon Dreams is a trading name for Pure Destinations Ltd whose registered address can be found on Companies House, Company No. 10604545
---------------------------
image URL
---------------------------
https://www.facebook.com/tr?id=120737145081077&ev=PageView


https://www.puredestinations.co.uk/wp-content/themes/puredestinations/images/logo/puredestinations.png

https://www.puredestinations.co.uk/wp-content/uploads/2016/11/INDIA-BLOG-HEADER-1600x500.jpg

http://www.puredestinations.co.uk/wp-content/uploads/2016/11/TAJ-MAHAL-PD-BLOG.jpg

http://www.puredestinations.co.uk/wp-content/uploads/2016/11/Golden-Temple-PD-BLOG.jpg

http://www.puredestinations.co.uk/wp-content/uploads/2016/11/meenakshi-temple-PD-BLOG.jpg

http://www.puredestinations.co.uk/wp-content/uploads/2016/11/Mysore-palace-PD-BLOG.jpg

http://www.puredestinations.co.uk/wp-content/uploads/2016/11/gateway-to-india-PD-BLOG.jpg

http://www.puredestinations.co.uk/wp-content/uploads/2016/11/red-fort-PD-BLOG.jpg

http://www.puredestinations.co.uk/wp-content/uploads/2016/11/HAWA-MAHAL-PD-BLOG.jpg

http://www.puredestinations.co.uk/wp-content/uploads/2016/11/qutub-minar-PD-BLOG.jpg

http://www.puredestinations.co.uk/wp-content/uploads/2016/11/Sanchi-Stupi-PD-BLOG.jpg

http://www.puredestinations.co.uk/wp-content/uploads/2016/11/Charminar-PD-BLOG-1.jpg

https://www.puredestinations.co.uk/wp-content/themes/puredestinations/images/accreditations/abta.png

https://www.puredestinations.co.uk/wp-content/themes/puredestinations/images/accreditations/protected.png
https://www.facebook.com/tr?id=106387616371570&ev=PageView